name: atcs
channels:
  - defaults
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  # numpy
  - numpy==1.21.2
  # pytorch
  - pytorch==1.11.0
  - torchtext==0.12.0
  - cudatoolkit==11.3.1
  # pytorch lightning
  - pytorch-lightning==1.6.0
  # scikit learn
  - scikit-learn==0.24.2
  # pandas
  - pandas==1.2.3
  # hugging face
  - datasets==1.18.4
  # nltk
  - nltk==3.6.7
  # spacy
  - spacy==2.3.7
  - cupy==9.6.0
  # tqdm
  - tqdm==4.63.0
  # jupyter
  - jupyter==1.0.0
  # python
  - python==3.8.13
